### ISSUE TITLE
Security updates ?

### ISSUE THREAD

**Issue by barkbay** [openshift/s2i-php#102]
Hi everyone,

Not sure this is the best place to ask the question but the version of PHP 5.5 used seems rather old : 

```
sh-4.2$ php --version                                                           
PHP 5.5.21 (cli) (built: Oct  5 2015 21:26:44)                                  
Copyright (c) 1997-2014 The PHP Group                                           
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies                   
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
```

There have been several releases that fix security problems : http://php.net/ChangeLog-5.php
Can someone may share the update policy ?

Thanks

**Comment by bparees** [comment]
@hhorak can you weigh in?

we use the SCL packaged php versions.

**Comment by hhorak** [comment]
@bparees is correct, in order to get newer packages to php container, we need to update the RPM packages in RHSCL first. That said, the capacity is limited and we're not able to keep all packages up2date every-time.
@barkbay If this issue is critical or in any way time sensitive, please raise a ticket through the regular Red Hat support channels to ensure it receives the proper attention and prioritization to assure a timely resolution. That is generally the best way to influence what gets fixed. For information on how to contact the Red Hat production support team, please visit: https://www.redhat.com/en/services/support

**Comment by barkbay** [comment]
@bparees @hhorak Thanks for the information.
